---
- name: multiple commands
  hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: run multiple commands
      ios_config:
        commands:
          - show ip interface brief
          - show cdp neighbour
          - show arp

      register: print_output

       debug: 
         var : print_output
