
---
iosv_l2:
  hostname: "192.168.122.201"
#  username: "rayka"
#  password: "rayka-co.com"
  groups:
    - cisco

ios_l3:
  hostname: "192.168.122.202"
#  username: "rayka"
#  password: "rayka-co.com"
  groups:
    - cisco

#hosts file contains our hosts details
#eg how to get to hosts and type of device cisco/junos etc